/*
 * generated by Xtext 2.9.0
 */
package com.incquerylabs.evm.xtext.example


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class ExampleLanguageRuntimeModule extends AbstractExampleLanguageRuntimeModule {
}
